#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export NVM_DIR="/usr/local/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

PATH="$HOME/.cargo/bin:/usr/lib/go-1.10/bin:$PATH"

# start ssh agent once login & kill ssh agent once exit
eval "$(ssh-agent -s)"
TRAPEXIT() {
  ssh-agent -k
}
